--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/shiv/Shiv/wallpapers/1066532.png"

-- Special
background="#030305"
foreground="#cee6e6"
cursor="#cee6e6"

-- Colors
color0="#030305"
color1="#B58571"
color2="#D09878"
color3="#EEDE52"
color4="#5F779B"
color5="#C6AF9A"
color6="#92B0D3"
color7="#cee6e6"
color8="#90a1a1"
color9="#B58571"
color10="#D09878"
color11="#EEDE52"
color12="#5F779B"
color13="#C6AF9A"
color14="#92B0D3"
color15="#cee6e6"
