# Shell variables
# Generated by 'wal'
wallpaper='/home/shiv/Shiv/wallpapers/1066532.png'

# Special
background='#030305'
foreground='#cee6e6'
cursor='#cee6e6'

# Colors
color0='#030305'
color1='#B58571'
color2='#D09878'
color3='#EEDE52'
color4='#5F779B'
color5='#C6AF9A'
color6='#92B0D3'
color7='#cee6e6'
color8='#90a1a1'
color9='#B58571'
color10='#D09878'
color11='#EEDE52'
color12='#5F779B'
color13='#C6AF9A'
color14='#92B0D3'
color15='#cee6e6'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
